json.id             item.id
json.product_id     item.variant&.product&.id
json.title          item.variant&.product&.title
json.original_price item.original_price
json.price          item.price
json.number         item.number
json.sku_value      item.sku_value
json.refunded       item.refunded
json.image          item.variant&.image&.preview